name: 'Clang Precompiled Action'
description: 'Action to install precompiled LLVM Clang'
author: 'MorganCaron'

branding:
  icon: 'download-cloud'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download LLVM Clang
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: main.yml
        workflow_conclusion: success
        name: llvm-clang-precompiled
        repo: MorganCaron/clang-precompiled-action
        check_artifacts: true
        search_artifacts: true
        allow_forks: false

    - name: Set LLVM Clang Path
      shell: bash
      run: |
        echo "::add-path::${GITHUB_WORKSPACE}/llvm/install/bin"
        echo "::add-path::${GITHUB_WORKSPACE}/llvm/install/lib/x86_64-unknown-linux-gnu"

    - name: Verify LLVM Clang Installation
      shell: bash
      run: |
        clang --version
        clang++ --version
