name: 'Install Latest Clang'
description: 'Action to install latest Clang'
author: 'MorganCaron'

branding:
  icon: 'download-cloud'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download LLVM Clang
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: main.yml
        workflow_conclusion: success
        name: llvm-clang
        repo: MorganCaron/latest-clang-action
        path: llvm/
        check_artifacts: true
        search_artifacts: true
        allow_forks: false

    - name: Adding Clang to Path
      shell: bash
      run: |
        chmod -R 755 llvm/
        export PATH=$PATH:$GITHUB_WORKSPACE/llvm/bin
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/llvm/lib/x86_64-unknown-linux-gnu
        sudo update-alternatives --install /usr/bin/clang clang $GITHUB_WORKSPACE/llvm/bin/clang 1000
        sudo update-alternatives --install /usr/bin/clang++ clang++ $GITHUB_WORKSPACE/llvm/bin/clang++ 1000

    - name: Verify Clang Installation
      shell: bash
      run: |
        clang --version
        clang++ --version
